services:
    dmzx.topicsubscribers.listener:
        class: dmzx\topicsubscribers\event\listener
        arguments:
            - '@user'
            - '@template'
            - '@dbal.conn'
            - '%core.adm_relative_path%'
        tags:
            - { name: event.listener }            